# Generated by Django 4.1 on 2022-08-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battute',
            name='testo',
            field=models.TextField(default=''),
        ),
    ]
