# Generated by Django 4.1 on 2022-08-19 03:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0002_battute_testo'),
    ]

    operations = [
        migrations.AddField(
            model_name='battute',
            name='tipo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sat', 'Satira'), ('Bar', 'Barzelletta'), ('Bhu', 'Black Humor'), ('Bsq', 'Battute Squallide')], default='bar', max_length=3),
        ),
        migrations.CreateModel(
            name='Recensioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator('1'), django.core.validators.MaxValueValidator('10')])),
                ('battuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esame.battute')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
