# Generated by Django 4.1 on 2022-08-20 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0004_profilodettagliato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensioni',
            name='voto',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
