# Generated by Django 4.1 on 2022-08-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0006_battute_media_voti_battute_numero_voti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battute',
            name='media_voti',
        ),
        migrations.RemoveField(
            model_name='battute',
            name='numero_voti',
        ),
        migrations.RemoveField(
            model_name='battute',
            name='somma_voti',
        ),
        migrations.AlterField(
            model_name='recensioni',
            name='battuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battuta_rec', to='esame.battute'),
        ),
    ]
