# Generated by Django 4.1 on 2022-08-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0009_alter_profilodettagliato_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilodettagliato',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
