# Generated by Django 4.1 on 2022-08-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0010_profilodettagliato_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilodettagliato',
            name='cognome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilodettagliato',
            name='datadinascita',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profilodettagliato',
            name='foto_profilo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profilodettagliato',
            name='nome',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
