# Generated by Django 4.1 on 2022-08-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0013_profilodettagliato_citta'),
    ]

    operations = [
        migrations.AddField(
            model_name='battute',
            name='utente_det',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='utentedet', to='esame.profilodettagliato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battute',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utentebat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilodettagliato',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profilodettagliato',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
