# Generated by Django 4.1 on 2022-08-21 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0014_battute_utente_det_alter_battute_utente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battute',
            name='utente_det',
        ),
        migrations.AlterField(
            model_name='profilodettagliato',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciao', to=settings.AUTH_USER_MODEL),
        ),
    ]
