# Generated by Django 4.1 on 2022-08-23 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0015_remove_battute_utente_det_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_seguito', to=settings.AUTH_USER_MODEL)),
                ('seguitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_seguitore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
