# Generated by Django 4.1 on 2022-08-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0016_followers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followers',
            constraint=models.UniqueConstraint(fields=('seguitore', 'seguito'), name='relazione di follow'),
        ),
    ]
