# Generated by Django 4.1 on 2022-08-23 17:09

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0017_followers_relazione di follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilodettagliato',
            name='utente',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciao', to=settings.AUTH_USER_MODEL),
        ),
    ]
