# Generated by Django 4.1 on 2022-08-23 17:12

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0018_alter_profilodettagliato_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilodettagliato',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilodettagliato',
            name='utente',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ciao', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
