# Generated by Django 4.1 on 2022-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0019_remove_profilodettagliato_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilodettagliato',
            name='datadinascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilodettagliato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profilodettagliato',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
