# Generated by Django 4.1 on 2022-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0020_alter_profilodettagliato_datadinascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battute',
            name='tipo',
            field=models.CharField(choices=[('Satira', 'Satira'), ('Barzelletta', 'Barzelletta'), ('Black humor', 'Black Humor'), ('Battuta squallida', 'Battuta Squallida'), ('Gioco di parole', 'Gioco di parole'), ('Notizia divertente', 'Notizia divertente')], default='bar', max_length=25),
        ),
    ]
