# Generated by Django 4.1 on 2022-09-02 00:20

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esame', '0021_alter_battute_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilodettagliato',
            name='utente',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
